2020-11-29 21:24:57,899	INFO services.py:1104 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
Traceback (most recent call last):
  File "train_wandb_impala.py", line 201, in <module>
    train_func()
  File "train_wandb_impala.py", line 159, in train_func
    "custom_model": config["model_net"],
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 127, in __getitem__
    return self._items[key]
KeyError: 'model_net'
